/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SelectRoleRouteImport } from './routes/select-role'
import { Route as RedeemRouteImport } from './routes/redeem'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VetIndexRouteImport } from './routes/vet.index'
import { Route as FarmerIndexRouteImport } from './routes/farmer.index'
import { Route as VetUploadRouteImport } from './routes/vet.upload'
import { Route as FarmerFeedRouteImport } from './routes/farmer.feed'
import { Route as FarmerDiseaseRouteImport } from './routes/farmer.disease'
import { Route as VetDiseasesIndexRouteImport } from './routes/vet.diseases.index'
import { Route as VetDiseasesSlugRouteImport } from './routes/vet.diseases.$slug'

const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectRoleRoute = SelectRoleRouteImport.update({
  id: '/select-role',
  path: '/select-role',
  getParentRoute: () => rootRouteImport,
} as any)
const RedeemRoute = RedeemRouteImport.update({
  id: '/redeem',
  path: '/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VetIndexRoute = VetIndexRouteImport.update({
  id: '/vet/',
  path: '/vet/',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerIndexRoute = FarmerIndexRouteImport.update({
  id: '/farmer/',
  path: '/farmer/',
  getParentRoute: () => rootRouteImport,
} as any)
const VetUploadRoute = VetUploadRouteImport.update({
  id: '/vet/upload',
  path: '/vet/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerFeedRoute = FarmerFeedRouteImport.update({
  id: '/farmer/feed',
  path: '/farmer/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerDiseaseRoute = FarmerDiseaseRouteImport.update({
  id: '/farmer/disease',
  path: '/farmer/disease',
  getParentRoute: () => rootRouteImport,
} as any)
const VetDiseasesIndexRoute = VetDiseasesIndexRouteImport.update({
  id: '/vet/diseases/',
  path: '/vet/diseases/',
  getParentRoute: () => rootRouteImport,
} as any)
const VetDiseasesSlugRoute = VetDiseasesSlugRouteImport.update({
  id: '/vet/diseases/$slug',
  path: '/vet/diseases/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/redeem': typeof RedeemRoute
  '/select-role': typeof SelectRoleRoute
  '/signup': typeof SignupRoute
  '/success': typeof SuccessRoute
  '/farmer/disease': typeof FarmerDiseaseRoute
  '/farmer/feed': typeof FarmerFeedRoute
  '/vet/upload': typeof VetUploadRoute
  '/farmer/': typeof FarmerIndexRoute
  '/vet/': typeof VetIndexRoute
  '/vet/diseases/$slug': typeof VetDiseasesSlugRoute
  '/vet/diseases/': typeof VetDiseasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/redeem': typeof RedeemRoute
  '/select-role': typeof SelectRoleRoute
  '/signup': typeof SignupRoute
  '/success': typeof SuccessRoute
  '/farmer/disease': typeof FarmerDiseaseRoute
  '/farmer/feed': typeof FarmerFeedRoute
  '/vet/upload': typeof VetUploadRoute
  '/farmer': typeof FarmerIndexRoute
  '/vet': typeof VetIndexRoute
  '/vet/diseases/$slug': typeof VetDiseasesSlugRoute
  '/vet/diseases': typeof VetDiseasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/redeem': typeof RedeemRoute
  '/select-role': typeof SelectRoleRoute
  '/signup': typeof SignupRoute
  '/success': typeof SuccessRoute
  '/farmer/disease': typeof FarmerDiseaseRoute
  '/farmer/feed': typeof FarmerFeedRoute
  '/vet/upload': typeof VetUploadRoute
  '/farmer/': typeof FarmerIndexRoute
  '/vet/': typeof VetIndexRoute
  '/vet/diseases/$slug': typeof VetDiseasesSlugRoute
  '/vet/diseases/': typeof VetDiseasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-login'
    | '/contact'
    | '/login'
    | '/profile'
    | '/redeem'
    | '/select-role'
    | '/signup'
    | '/success'
    | '/farmer/disease'
    | '/farmer/feed'
    | '/vet/upload'
    | '/farmer/'
    | '/vet/'
    | '/vet/diseases/$slug'
    | '/vet/diseases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-login'
    | '/contact'
    | '/login'
    | '/profile'
    | '/redeem'
    | '/select-role'
    | '/signup'
    | '/success'
    | '/farmer/disease'
    | '/farmer/feed'
    | '/vet/upload'
    | '/farmer'
    | '/vet'
    | '/vet/diseases/$slug'
    | '/vet/diseases'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/admin-login'
    | '/contact'
    | '/login'
    | '/profile'
    | '/redeem'
    | '/select-role'
    | '/signup'
    | '/success'
    | '/farmer/disease'
    | '/farmer/feed'
    | '/vet/upload'
    | '/farmer/'
    | '/vet/'
    | '/vet/diseases/$slug'
    | '/vet/diseases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RedeemRoute: typeof RedeemRoute
  SelectRoleRoute: typeof SelectRoleRoute
  SignupRoute: typeof SignupRoute
  SuccessRoute: typeof SuccessRoute
  FarmerDiseaseRoute: typeof FarmerDiseaseRoute
  FarmerFeedRoute: typeof FarmerFeedRoute
  VetUploadRoute: typeof VetUploadRoute
  FarmerIndexRoute: typeof FarmerIndexRoute
  VetIndexRoute: typeof VetIndexRoute
  VetDiseasesSlugRoute: typeof VetDiseasesSlugRoute
  VetDiseasesIndexRoute: typeof VetDiseasesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-role': {
      id: '/select-role'
      path: '/select-role'
      fullPath: '/select-role'
      preLoaderRoute: typeof SelectRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redeem': {
      id: '/redeem'
      path: '/redeem'
      fullPath: '/redeem'
      preLoaderRoute: typeof RedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vet/': {
      id: '/vet/'
      path: '/vet'
      fullPath: '/vet/'
      preLoaderRoute: typeof VetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/': {
      id: '/farmer/'
      path: '/farmer'
      fullPath: '/farmer/'
      preLoaderRoute: typeof FarmerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vet/upload': {
      id: '/vet/upload'
      path: '/vet/upload'
      fullPath: '/vet/upload'
      preLoaderRoute: typeof VetUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/feed': {
      id: '/farmer/feed'
      path: '/farmer/feed'
      fullPath: '/farmer/feed'
      preLoaderRoute: typeof FarmerFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/disease': {
      id: '/farmer/disease'
      path: '/farmer/disease'
      fullPath: '/farmer/disease'
      preLoaderRoute: typeof FarmerDiseaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vet/diseases/': {
      id: '/vet/diseases/'
      path: '/vet/diseases'
      fullPath: '/vet/diseases/'
      preLoaderRoute: typeof VetDiseasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vet/diseases/$slug': {
      id: '/vet/diseases/$slug'
      path: '/vet/diseases/$slug'
      fullPath: '/vet/diseases/$slug'
      preLoaderRoute: typeof VetDiseasesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AdminLoginRoute: AdminLoginRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RedeemRoute: RedeemRoute,
  SelectRoleRoute: SelectRoleRoute,
  SignupRoute: SignupRoute,
  SuccessRoute: SuccessRoute,
  FarmerDiseaseRoute: FarmerDiseaseRoute,
  FarmerFeedRoute: FarmerFeedRoute,
  VetUploadRoute: VetUploadRoute,
  FarmerIndexRoute: FarmerIndexRoute,
  VetIndexRoute: VetIndexRoute,
  VetDiseasesSlugRoute: VetDiseasesSlugRoute,
  VetDiseasesIndexRoute: VetDiseasesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
